dist: trusty
sudo: required
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"

script:
- mvn clean package -Pcoverage
- mvn sonar:sonar -Psonar -Dsonar.organization=mobi-challenge -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_KEY}
